partnr = 10     # Count of particles
fps = 60
r = 0.2         # Radius of particle in meter
h = 1           # Radius of search in meter
m = 70          # Mass in kg
sl = 2          # Multiplier on the random start speed
strength = 10    # Multiplier on the force between particles
wallf = 1.0     # Walls repellant force
cutoff = 5      # Threshold of proximity
long_strength = 0.5  # Multiplier on the force between distant particles
long_cutoff = 10     # Threshold of proximity of distant particles
goal_x = 45.5   # Center of the exit gap
goal_y = 91.0
v_pref = 1.4    # Preferred speed in m/s (matches paper)
tau   = 0.5     # Relaxation time — how quickly particle steers toward goal. "Smoothing" force so they are gentle
rho0  = 1.0    # Rest density (P/m²) — target crowd density
k_sph = 1.0    # Gas constant — stiffness of pressure response
mu = 5.0        # Viscosity — dampens relative motion between neighbors